name: Deploy Swagger UI to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install swagger-cli
        run: npm install -g swagger-cli

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: docs/api/openapi.yaml

      - name: Validate OpenAPI definition
        run: go run github.com/getkin/kin-openapi/cmd/validate@latest -- docs/api/openapi.yaml

      - name: Upload Documents
        uses: actions/upload-pages-artifact@v1
        with:
          path: swagger-ui
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
